 
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template EC2_Instance_With_Ephemeral_Drives:
  Example to show how to attach ephemeral drives using EC2 block device mappings.
  **WARNING** This template creates an Amazon EC2 instance. You will be billed for
  the AWS resources used if you create a stack from this template.'
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0742b4e673072066f
      InstanceType: t2.micro
      KeyName: FetchReward
      BlockDeviceMappings: 
      - DeviceName: "/dev/xvda"
        Ebs: 
          VolumeType: "io1"
          Iops: "200"
          DeleteOnTermination: "false"
          VolumeSize: "10"
      - DeviceName: "/dev/xvdf"
        Ebs: 
          VolumeType: "io1"
          Iops: "100"
          DeleteOnTermination: "false"
          VolumeSize: "8"
